# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Mon, 03 Aug 2015 00:28:31 +0000
*               @ALL          1
*               @user         8
