<?php
/**
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by install script
 * Date: Mon, 03 Aug 2015 00:28:31 +0000
 */
$conf['title'] = 'Documentación Ararauna';
$conf['lang'] = 'es';
$conf['license'] = 'gnufdl';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
